'''OpenGL extension SGIX.FfdMask

The official definition of this extension is available here:
	http://oss.sgi.com/projects/ogl-sample/registry/SGIX/FfdMask.txt

Automatically generated by the get_gl_extensions script, do not edit!
'''
from OpenGL import platform, constants, constant, arrays
from OpenGL import extensions
from OpenGL.GL import glget
import ctypes
GL_TEXTURE_DEFORMATION_BIT_SGIX = constant.Constant( 'GL_TEXTURE_DEFORMATION_BIT_SGIX', 0x1 )
GL_GEOMETRY_DEFORMATION_BIT_SGIX = constant.Constant( 'GL_GEOMETRY_DEFORMATION_BIT_SGIX', 0x2 )


def glInitFfdmaskSGIX():
	'''Return boolean indicating whether this extension is available'''
	return extensions.hasGLExtension( 'GL_SGIX_FfdMask' )
