'''OpenGL extension INGR.blend_func_separate

The official definition of this extension is available here:
	http://oss.sgi.com/projects/ogl-sample/registry/INGR/blend_func_separate.txt

Automatically generated by the get_gl_extensions script, do not edit!
'''
from OpenGL import platform, constants, constant, arrays
from OpenGL import extensions
from OpenGL.GL import glget
import ctypes

glBlendFuncSeparateINGR = platform.createExtensionFunction( 
	'glBlendFuncSeparateINGR', dll=platform.GL,
	resultType=None, 
	argTypes=(constants.GLenum, constants.GLenum, constants.GLenum, constants.GLenum,),
	doc = 'glBlendFuncSeparateINGR( GLenum(sfactorRGB), GLenum(dfactorRGB), GLenum(sfactorAlpha), GLenum(dfactorAlpha) ) -> None',
	argNames = ('sfactorRGB', 'dfactorRGB', 'sfactorAlpha', 'dfactorAlpha',),
)


def glInitBlendFuncSeparateINGR():
	'''Return boolean indicating whether this extension is available'''
	return extensions.hasGLExtension( 'GL_INGR_blend_func_separate' )
